export const getDayCardData = () => {
    return [
        {
            platform:'虎嗅',
            newsTitle:[
                {
                    new:'测试测试测试测试测试测试测试测试1'
                },
                {
                    new:'测试测试测试测试测试测试测试测试2'
                },
                {
                    new:'测试测试测试测试测试测试测试测试3'
                },
                {
                    new:'测试测试测试测试测试测试测试测试4'
                }
            ]
        },
        {
            platform:'知乎',
            newsTitle:[
                {
                    new:'测试测试测试测试测试测试测试测试5'
                },
                {
                    new:'测试测试测试测试测试测试测试测试6'
                }
            ]
        }
    ]
}